version: '3'
services:
  springfarm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/usr/src/app
    command: yarn start
    container_name: springfarm
    ports:
     - "3000:3000"
    tty: true
